	/*
	 * This is sample code generated by rpcgen.
	 * These are only templates and you can use them
	 * as a guideline for developing your own functions.
	 */

	#include "calc.h"

	float *
	calculadora_1_svc(struct Parametros *argp, struct svc_req *rqstp)
	{
		static float  result;

		switch((int)argp->opc){
		
			case 1:
					result=argp->a+argp->b;
			break;

			case 2:
			
					result=argp->a-argp->b;
			break;

			case 3:

					result=argp->a*argp->b;

			break;

			case 4:
					if((int)argp->b==0){
						printf("No se puede divir entre 0");
						exit -1;
					}
					result=(float)argp->a/(float)argp->b;

			break;

			default:
			printf("Opcion incorrecta");
			break;
		}
		return &result;
	}
