/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Parametros {
	int a;
	int b;
	int opc;
};
typedef struct Parametros Parametros;

#define calc 1
#define calc_ver 1

#if defined(__STDC__) || defined(__cplusplus)
#define Calculadora 1
extern  float * calculadora_1(struct Parametros *, CLIENT *);
extern  float * calculadora_1_svc(struct Parametros *, struct svc_req *);
extern int calc_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Calculadora 1
extern  float * calculadora_1();
extern  float * calculadora_1_svc();
extern int calc_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Parametros (XDR *, Parametros*);

#else /* K&R C */
extern bool_t xdr_Parametros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
