/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include "string.h"
#include "ctype.h"
void calc_1(char *host, int x, int y, int z)
{
	CLIENT *clnt;
	float *result_1;
	struct Parametros calculadora_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, calc, calc_ver, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	calculadora_1_arg.a = x;
	calculadora_1_arg.b = y;
	calculadora_1_arg.opc = z;
	result_1 = calculadora_1(&calculadora_1_arg, clnt);
	if (result_1 == (float *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	if ((int)*result_1 == -1)
	{
		printf("No se puede dividir entre cero\n");
	}
	else
	{
		printf("EL resultado es %f\n", *result_1);
	}

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int valida_numero(char *numero);
int main(int argc, char *argv[])
{
	char *host;
	char aux1[40], aux2[40], aux3[40];
	int x, y, z, n;
	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	printf("\t------------------Calculadora----------------------- \n");
	printf("\t----------------------------------------------------\n");
	do
	{
		printf("\nValor 1 ----->");
		scanf("%s", aux1);
		n = valida_numero(aux1);
	} while (n == 0);
	x = atoi(aux1);
	do
	{
		printf("\nValor 2 ----->");
		scanf("%s", aux2);
		n = valida_numero(aux2);
	} while (n == 0);
	y = atoi(aux2);

	do
	{
		printf("\n\t---------------------MENU--------------------------- \n");
		printf("1. SUMA\n");
		printf("2. RESTA\n");
		printf("3. MULTIPLICACION\n");
		printf("4. DIVISION\n");
		scanf("%s", aux3);
		n = valida_numero(aux3);

	} while (n == 0);
	z = atoi(aux3);
	calc_1(host, x, y, z);
	exit(0);
}
int valida_numero(char *numero)
{
	int i;
	for (i = 0; i < strlen(numero); i++)
	{
		if (!(isdigit(numero[i])))
		{
			printf("\nIngresa solo numeros\n");
			fflush(stdin);
			getchar();
			getchar();
			return 0;
		}
	}
	return 1;
}